apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: platform-app
  template:
    metadata:
      labels:
        app: platform-app
    spec:
      containers:
      - name: platform-app
        image: dineshpatil0908/gitops-platform-app:v3
        ports:
        - containerPort: 8000
